"""Checks for the BAB strategy machinery in bab.py.

Every case here has an answer worked out independently of the code under test:
either a hand-computed number, or a simulation whose data-generating process
fixes what the answer has to be. Run with `python test_bab.py`.
"""

import warnings

import numpy as np
import pandas as pd

import bab


def _panel(n_firms=50, n_months=120, seed=0, alpha_per_beta=0.0,
           alpha_const=0.0):
    """Simulate a panel where returns really are generated by a known beta.

    Firm i has a fixed true beta and earns

        ret = alpha_const + alpha_per_beta * beta + beta * mkt + noise

    The two alphas are different deviations from the CAPM and the two
    strategies see different ones, which the tests below pin down:

    `alpha_const` tilts the security market line's intercept without changing
    its slope. This is the Frazzini-Pedersen story: a low-beta stock levered up
    to beta one earns alpha_const / beta_low, a high-beta stock levered down
    earns the smaller alpha_const / beta_high, so the levered factor is
    positive. It cancels out of an unlevered Q5-minus-Q1 difference.

    `alpha_per_beta` rotates the line through the intercept, so it is absorbed
    entirely when each leg is levered to beta one, but survives in the spread.
    """
    rng = np.random.default_rng(seed)
    betas = np.linspace(0.3, 2.0, n_firms)
    mkt = rng.normal(0.007, 0.045, n_months)

    rows = []
    for i in range(n_firms):
        eps = rng.normal(0, 0.06, n_months)
        ret = (alpha_const + alpha_per_beta * betas[i]
               + betas[i] * mkt + eps)
        for t in range(n_months):
            rows.append({
                "PERMNO": 1000 + i,
                "year": 2005 + t // 12,
                "month": t % 12 + 1,
                "ret": ret[t],
                "mkt": mkt[t],
                "beta": betas[i],
                "mktcap": 1e6 * (i + 1),
            })
    return bab.prepare_panel(pd.DataFrame(rows))


def test_quantiles_are_formed_within_month():
    """Ranking must happen inside each month, not across the pooled panel."""
    # Betas drift upward over time, so a pooled sort would put every early
    # month in the bottom bucket and every late month in the top one.
    rows = []
    for t in range(24):
        for i in range(10):
            rows.append({"PERMNO": i, "year": 2005 + t // 12, "month": t % 12 + 1,
                         "ret": 0.0, "beta": t * 10 + i, "mktcap": 1.0})
    panel = bab.prepare_panel(pd.DataFrame(rows))
    panel["q"] = bab.assign_quantiles(panel, "beta", 5)

    per_month = panel.groupby("t")["q"].nunique()
    assert (per_month == 5).all(), "every month must span all five buckets"

    # Within a month, the highest beta is in the top bucket.
    first = panel[panel["t"] == panel["t"].min()]
    assert first.loc[first["beta"].idxmax(), "q"] == 5
    assert first.loc[first["beta"].idxmin(), "q"] == 1
    print("ok  quantiles are formed within each month")


def test_equal_weighted_returns_match_hand_computation():
    rows = []
    for i, (beta, ret) in enumerate([(0.5, 0.01), (0.8, 0.02),
                                     (1.2, 0.03), (1.9, 0.10)]):
        rows.append({"PERMNO": i, "year": 2020, "month": 1,
                     "ret": ret, "beta": beta, "mktcap": 1.0})
    panel = bab.prepare_panel(pd.DataFrame(rows))
    res = bab.quantile_portfolios(panel, n_portfolios=2, weight="ew",
                                  warn_thin=0)

    # Two buckets of two: low = (0.01 + 0.02)/2, high = (0.03 + 0.10)/2.
    assert np.isclose(res.returns["q1"].iloc[0], 0.015)
    assert np.isclose(res.returns["q2"].iloc[0], 0.065)
    assert np.isclose(res.returns["spread"].iloc[0], 0.05)
    print("ok  equal-weighted bucket returns match hand computation")


def test_value_weights_use_the_lagged_market_cap():
    """A stock's own holding-month return must not set its own weight."""
    rows = [
        # Small in December, huge in January after a large January return.
        {"PERMNO": 1, "year": 2019, "month": 12, "ret": 0.00, "beta": 1.0, "mktcap": 100.0},
        {"PERMNO": 1, "year": 2020, "month": 1, "ret": 0.50, "beta": 1.0, "mktcap": 10_000.0},
        {"PERMNO": 2, "year": 2019, "month": 12, "ret": 0.00, "beta": 1.1, "mktcap": 100.0},
        {"PERMNO": 2, "year": 2020, "month": 1, "ret": -0.10, "beta": 1.1, "mktcap": 90.0},
    ]
    panel = bab.prepare_panel(pd.DataFrame(rows))
    jan = panel[panel["month"] == 1].copy()
    jan["q"] = 1.0

    res = bab.quantile_portfolios(jan, n_portfolios=1, weight="vw",
                                  quantile_col="q", warn_thin=0)
    got = res.returns["q1"].iloc[0]

    # Formation caps are equal at 100 each, so this is a straight average.
    assert np.isclose(got, 0.20), f"expected 0.20 with lagged caps, got {got}"
    # Contemporaneous caps would have given ~0.4947, dominated by the winner.
    assert not np.isclose(got, 0.4947, atol=1e-3)
    print("ok  value weights use the market cap known at formation")


def test_bab_legs_are_normalised_and_beta_neutral():
    panel = _panel(n_firms=40, n_months=60, seed=7)
    out = bab.bab_factor(panel, rf=None)

    assert len(out) == 60
    # The low leg holds lower betas than the high leg, every month.
    assert (out["beta_low"] < out["beta_high"]).all()
    # Levering each leg to one leaves the factor with no net market exposure.
    net = out["beta_low"] * out["lev_low"] - out["beta_high"] * out["lev_high"]
    assert np.allclose(net, 0.0, atol=1e-9), f"net beta not zero: {net.abs().max()}"
    print("ok  BAB legs are normalised and the factor is ex-ante beta neutral")


def test_bab_weights_sum_to_one_on_each_side():
    """Reproduce the rank weighting by hand for a single month."""
    betas = np.array([0.4, 0.8, 1.2, 1.6, 2.0])
    z = pd.Series(betas).rank(method="first")
    zbar = z.mean()
    k = 2.0 / (z - zbar).abs().sum()
    w_hi = np.maximum(z - zbar, 0) * k
    w_lo = np.maximum(zbar - z, 0) * k

    assert np.isclose(w_hi.sum(), 1.0), w_hi.sum()
    assert np.isclose(w_lo.sum(), 1.0), w_lo.sum()
    # The scaling constant k is what makes each side sum to one; confirm the
    # module's own output agrees on a panel built from these betas.
    rows = [{"PERMNO": i, "year": 2020, "month": 1, "ret": 0.01 * i,
             "beta": b, "mktcap": 1.0} for i, b in enumerate(betas)]
    panel = bab.prepare_panel(pd.DataFrame(rows))
    out = bab.bab_factor(panel)
    expected_hi = float((w_hi / w_hi.sum() * betas).sum())
    assert np.isclose(out["beta_high"].iloc[0], expected_hi)
    print("ok  BAB rank weights sum to one on each side")


def test_flat_sml_shows_up_in_bab_but_not_in_the_raw_spread():
    """The Frazzini-Pedersen effect is only visible once the legs are levered.

    Plant a constant 40bps alpha shared by every stock, so the security market
    line is too flat. Levered to beta one, the low-beta leg earns
    0.004 / beta_low and the high-beta leg only 0.004 / beta_high, so BAB is
    positive. In an unlevered Q5-minus-Q1 difference the constant cancels and
    the effect is invisible, however the returns are adjusted afterwards.
    """
    const = 0.004
    panel = _panel(n_firms=80, n_months=180, seed=3, alpha_const=const)
    mkt = panel.groupby("t")["mkt"].first()
    factors = pd.DataFrame({"mkt": mkt})

    factor = bab.bab_factor(panel)
    neutral = bab.newey_west_mean(factor["bab"])
    expected = const * (1.0 / factor["beta_low"].mean()
                        - 1.0 / factor["beta_high"].mean())
    assert neutral["mean"] > 0, neutral
    assert neutral["tstat"] > 3, neutral
    assert np.isclose(neutral["mean"], expected, atol=0.002), \
        f"got {neutral['mean']:.4f}, expected about {expected:.4f}"

    res = bab.quantile_portfolios(panel, n_portfolios=5, weight="ew")
    adj = bab.factor_alpha(res.returns["spread"], factors)
    assert abs(adj["alpha"]) < 0.002, \
        f"the constant should cancel in the spread, got {adj['alpha']:.4f}"

    print(f"ok  flat SML found by BAB ({neutral['mean']:+.4f} vs "
          f"{expected:+.4f} expected, t={neutral['tstat']:.2f}) and invisible "
          f"to the raw spread (alpha {adj['alpha']:+.4f})")


def test_beta_proportional_alpha_shows_up_in_the_spread_but_not_in_bab():
    """The converse, and the reason to report both constructions.

    An alpha proportional to beta is just a different market risk premium: the
    line still passes through the intercept, so levering each leg to beta one
    removes it exactly and BAB reads zero. The spread's market-adjusted alpha
    is where it shows up.
    """
    per_beta = -0.003
    panel = _panel(n_firms=80, n_months=180, seed=3, alpha_per_beta=per_beta)
    mkt = panel.groupby("t")["mkt"].first()
    factors = pd.DataFrame({"mkt": mkt})

    res = bab.quantile_portfolios(panel, n_portfolios=5, weight="ew")
    raw = bab.newey_west_mean(res.returns["spread"])
    adj = bab.factor_alpha(res.returns["spread"], factors)

    # The raw spread has the wrong sign: it is long about 1.5 units of a market
    # earning 0.7% a month, worth +105bps against the planted -45bps. Reporting
    # an unadjusted Q5-minus-Q1 number measures market exposure, not the anomaly.
    assert raw["mean"] > 0, raw
    assert adj["alpha"] < 0, adj
    assert adj["alpha_t"] < -2, adj

    spread_beta = (res.mean_beta["q5"] - res.mean_beta["q1"]).mean()
    assert np.isclose(adj["alpha"], per_beta * spread_beta, atol=0.002), adj

    factor = bab.bab_factor(panel)
    neutral = bab.newey_west_mean(factor["bab"])
    assert abs(neutral["tstat"]) < 2.5, \
        f"leverage should absorb a beta-proportional alpha: {neutral}"

    print(f"ok  beta-proportional alpha found in the spread's alpha "
          f"({adj['alpha']:+.4f} t={adj['alpha_t']:.2f}), raw spread has the "
          f"wrong sign ({raw['mean']:+.4f}), BAB absorbs it "
          f"(t={neutral['tstat']:.2f})")


def test_no_effect_means_no_spread():
    """With alpha_per_beta = 0 the CAPM holds and the spread is just market
    exposure, so the beta-neutral BAB factor should not be significant."""
    panel = _panel(n_firms=80, n_months=240, seed=11, alpha_per_beta=0.0)
    factor = bab.bab_factor(panel)
    stats = bab.newey_west_mean(factor["bab"])
    assert abs(stats["tstat"]) < 2.5, f"false positive under the null: {stats}"
    print(f"ok  no planted effect gives an insignificant BAB (t={stats['tstat']:.2f})")


def test_rolling_ols_recovers_the_true_beta_and_looks_backward():
    panel = _panel(n_firms=20, n_months=160, seed=5)
    panel["beta_ols"] = bab.rolling_ols_beta(panel, window=60, min_periods=36)

    fitted = panel.dropna(subset=["beta_ols"])
    err = fitted["beta_ols"] - fitted["beta"]

    # With 6% idiosyncratic vol, 4.5% market vol and a 60-month window, the
    # standard error on a regression beta is 0.06 / (0.045 * sqrt(60)) = 0.17.
    # The estimator cannot beat that, so test what it can be held to: no bias,
    # dispersion within sampling error, and a faithful cross-sectional ranking.
    se = 0.06 / (0.045 * np.sqrt(60))
    # Averaged over 20 firms the mean error has a standard error of about
    # se / sqrt(20) = 0.04, so anything inside 0.06 is consistent with no bias.
    assert abs(err.mean()) < 0.06, f"biased: mean error {err.mean():.3f}"
    assert err.abs().median() < se, f"median error {err.abs().median():.3f} vs se {se:.3f}"

    # Estimation noise caps the achievable correlation at
    # sd_true / sqrt(sd_true^2 + se^2) = 0.95 here, so 0.90 leaves room for
    # the shorter windows without letting a broken estimator through.
    corr = fitted["beta_ols"].corr(fitted["beta"])
    assert corr > 0.90, f"ranking not preserved: corr {corr:.3f}"

    # The first 36 months of every firm have no beta, because the window ends
    # at t-1 and needs 36 observations.
    first = panel.groupby("PERMNO").head(36)
    assert first["beta_ols"].isna().all(), "rolling beta must not peek forward"

    # A firm's window must not absorb the previous firm's returns.
    per_firm_first_valid = panel.groupby("PERMNO")["beta_ols"].apply(
        lambda s: s.notna().idxmax() - s.index[0]
    )
    assert (per_firm_first_valid >= 36).all()
    print(f"ok  rolling OLS beta recovers the truth (median error "
          f"{err.abs().median():.3f} vs {se:.3f} sampling error, corr {corr:.3f}), "
          f"uses only past data")


def test_turnover_and_drawdown():
    w = pd.DataFrame({"A": [0.5, 0.5, 0.0], "B": [0.5, 0.0, 0.5],
                      "C": [0.0, 0.5, 0.5]}, index=[1, 2, 3])
    tno = bab.turnover(w)
    # Month 2: B goes 0.5 -> 0, C goes 0 -> 0.5, so 1.0 traded in total.
    assert np.isclose(tno.loc[2], 1.0), tno
    assert np.isclose(tno.loc[3], 1.0), tno

    r = pd.Series([0.10, -0.50, 0.20])
    # Peak after month 1 is 1.10, trough after month 2 is 0.55: -50%.
    assert np.isclose(bab.max_drawdown(r), -0.5)
    print("ok  turnover and drawdown match hand computation")


def test_costs_reduce_returns_and_breakeven_is_consistent():
    r = pd.Series(np.full(120, 0.01))
    tno = pd.Series(np.full(120, 2.0), index=r.index)
    summary = bab.performance_summary(r, "test", turnover_series=tno,
                                      cost_bps=10.0)
    # 2.0 turnover at 10bps costs 20bps a month against a 100bps gross return.
    assert np.isclose(summary["net_mean_monthly"], 0.008)
    # Break-even is the cost that wipes out the gross return: 100bps / 2.0.
    assert np.isclose(summary["breakeven_cost_bps"], 50.0)
    print("ok  costs and break-even cost are consistent")


def test_factor_alpha_strips_market_exposure():
    rng = np.random.default_rng(42)
    mkt = rng.normal(0.006, 0.04, 240)
    true_alpha, true_beta = 0.004, 0.8
    r = true_alpha + true_beta * mkt + rng.normal(0, 0.01, 240)

    factors = pd.DataFrame({"mkt": mkt})
    out = bab.factor_alpha(pd.Series(r), factors)
    assert np.isclose(out["alpha"], true_alpha, atol=0.001), out
    assert np.isclose(out["b_mkt"], true_beta, atol=0.05), out
    assert out["alpha_t"] > 2
    print(f"ok  factor alpha recovers the planted alpha "
          f"({out['alpha']:.4f} vs {true_alpha})")


def test_raw_spread_carries_market_exposure_that_bab_removes():
    """The reason a raw Q5-Q1 sort is not a clean test of the CAPM."""
    panel = _panel(n_firms=80, n_months=240, seed=17, alpha_per_beta=0.0)
    res = bab.quantile_portfolios(panel, n_portfolios=5, weight="ew")

    mkt = panel.groupby("t")["mkt"].first()
    factors = pd.DataFrame({"mkt": mkt})

    spread = bab.factor_alpha(res.returns["spread"], factors)
    factor = bab.bab_factor(panel)
    neutral = bab.factor_alpha(factor["bab"], factors)

    # The raw spread is long about 1.5 units of market; BAB is near zero.
    assert spread["b_mkt"] > 1.0, spread
    assert abs(neutral["b_mkt"]) < 0.25, neutral
    print(f"ok  raw spread loads {spread['b_mkt']:.2f} on the market, "
          f"BAB loads {neutral['b_mkt']:.2f}")


def test_fama_french_percent_files_are_rescaled(tmp="/tmp/_ff_test.csv"):
    pd.DataFrame({"date": [202001, 202002, 202003],
                  "Mkt-RF": [-0.11, -8.13, -13.39],
                  "SMB": [-0.24, 0.94, -5.19],
                  "HML": [-6.23, -3.90, -14.02],
                  "RF": [0.13, 0.12, 0.13]}).to_csv(tmp, index=False)
    ff = bab.load_fama_french(tmp)
    assert np.isclose(ff["Mkt-RF"].iloc[1], -0.0813), ff
    assert np.isclose(ff["RF"].iloc[0], 0.0013), ff
    assert list(ff["year"]) == [2020, 2020, 2020]
    assert list(ff["month"]) == [1, 2, 3]

    # A file already in decimals must be left alone.
    pd.DataFrame({"date": [202001, 202002],
                  "Mkt-RF": [-0.0011, -0.0813],
                  "RF": [0.0013, 0.0012]}).to_csv(tmp, index=False)
    ff2 = bab.load_fama_french(tmp)
    assert np.isclose(ff2["Mkt-RF"].iloc[1], -0.0813), ff2
    print("ok  Fama-French percent files are rescaled, decimals left alone")


def test_thin_cross_section_warns():
    """80 survivor firms give 16 names a bucket; the code should say so."""
    panel = _panel(n_firms=20, n_months=24, seed=1)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        bab.quantile_portfolios(panel, n_portfolios=5, weight="ew")
    assert any("cross-section" in str(w.message) for w in caught), caught
    print("ok  a thin cross-section raises a warning")


def test_month_index_round_trips_through_december():
    """December must decode back to December, not to the following January."""
    rows = [{"PERMNO": 1, "year": y, "month": m, "ret": 0.0,
             "beta": 1.0, "mktcap": 1.0}
            for y in (2019, 2020) for m in range(1, 13)]
    panel = bab.prepare_panel(pd.DataFrame(rows))

    years, months = bab.decode_month(panel["t"].to_numpy())
    assert (years == panel["year"].to_numpy()).all()
    assert (months == panel["month"].to_numpy()).all()

    # Consecutive months must be one apart, including across the year boundary.
    assert (np.diff(np.sort(panel["t"].unique())) == 1).all()

    dec = panel[(panel["year"] == 2019) & (panel["month"] == 12)]["t"].iloc[0]
    jan = panel[(panel["year"] == 2020) & (panel["month"] == 1)]["t"].iloc[0]
    assert jan == dec + 1
    assert bab.decode_month(np.array([dec]))[0][0] == 2019
    print("ok  month index round-trips across the December boundary")


def test_keyed_arrays_align_betas_to_the_right_firm_month():
    """The keys must follow the samples, and the old offset must not.

    Three firms with different history lengths. Each loses its first `lookback`
    months, so the rows dropped are spread through the panel rather than
    sitting at the top of it.
    """
    import polars as pl

    lookback = 3
    lengths = {101: 10, 102: 7, 103: 12}
    rows = []
    for permno, n in lengths.items():
        for k in range(n):
            rows.append({
                "PERMNO": permno,
                "year": 2020 + k // 12,
                "month": k % 12 + 1,
                "RETX": permno / 1000.0 + k / 100.0,   # unique per firm-month
                "vwretd": 0.01 * k,
                "industry_Mining": 1,
                "industry_Retail": 0,
            })
    df = pl.DataFrame(rows)

    X, r_next, mkt_next, keys = bab.build_keyed_arrays(df, lookback=lookback)

    expected_n = sum(n - lookback for n in lengths.values())
    assert len(keys) == expected_n == len(X), (len(keys), expected_n)

    # Each firm contributes exactly its own months from `lookback` onwards.
    for permno, n in lengths.items():
        got = keys[keys["PERMNO"] == permno]
        assert len(got) == n - lookback
        assert list(got["month"]) == [k % 12 + 1 for k in range(lookback, n)]

    # The target really is the return of the firm-month named in the key, and
    # the features really are the three months before it.
    src = {(row["PERMNO"], row["year"], row["month"]): row["RETX"] for row in rows}
    for i in range(len(keys)):
        key = tuple(keys.iloc[i][["PERMNO", "year", "month"]])
        assert np.isclose(r_next[i], src[key]), f"target misaligned at {key}"
    # Firm 102's first sample: months 1-3 of its own history, nothing borrowed.
    first_102 = keys.index[keys["PERMNO"] == 102][0]
    assert np.allclose(X[first_102, :lookback],
                       [0.102 + k / 100.0 for k in range(lookback)])

    # Now the offset the notebook used: drop `total dropped` rows from the top.
    panel = df.sort(["PERMNO", "year", "month"]).select(
        ["PERMNO", "year", "month"]).to_pandas()
    offset = len(panel) - len(keys)
    implied = panel.iloc[offset:].reset_index(drop=True)
    wrong = (implied.to_numpy() != keys.to_numpy()).any(axis=1)

    assert wrong.any(), "the offset should misalign when firms differ in length"
    print(f"ok  keyed arrays align to the right firm-month; the offset "
          f"approach misplaces {wrong.mean():.0%} of them")


if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    for fn in tests:
        fn()
    print(f"\n{len(tests)} checks passed")
